version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Exposing backend on port 8000
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"  # Exposing Streamlit frontend on port 8501
    depends_on:
      - backend  # Ensure the backend starts first
    volumes:
      - ./frontend:/app
    environment:
      BACKEND_URL: "http://backend:8000"  # Point to backend service inside the Docker network
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
